/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unipampa.sgc.apresentacao;

/**
 *
 * @author GabrielBMoro
 */
public class JanelaCriarConcurso extends javax.swing.JFrame {

    public static int STATUS_CRIACAO_CONCURSO = 0;

    /**
     * Creates new form JFrameCriarConcurso
     */
    public JanelaCriarConcurso() {
        initComponents();
        setTitle("Criar Concurso");
        panelCriarConcurso1.getPanelDadosGerais().setVisible(true);
        panelCriarConcurso1.getPanelBanca().setVisible(false);
        panelCriarConcurso1.getPaneCandidatosInscritos().setVisible(false);
        panelCriarConcurso1.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public panelCriarConcurso getPanelCriarConcurso() {
        return this.panelCriarConcurso1;
    }

}
