/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unipampa.sgc.apresentacao;

/**
 *
 * @author GabrielBMoro
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
        ConfigurarFrame.configurarJanelaPadrao(this, 950, 681);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jTabbedPaneInternoDinamico = new javax.swing.JTabbedPane();
        jPanelSessaoDeAbertura = new javax.swing.JPanel();
        jPanelButtonsSessaoAbertura = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanelInternoSessaoAbertura = new javax.swing.JPanel();
        jPaneInstalacaoSessaoAbertura = new javax.swing.JPanel();
        txtHoraInicioSessaoInstalacao = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLocalSessaoInstalacao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPortariaNomeacaoDaBanca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPortariaNomeacaoBanca = new javax.swing.JTextField();
        btnSalvarInstalacaoSessao = new javax.swing.JButton();
        btnGerarAtaInstalacaoSessaoAbertura = new javax.swing.JButton();
        jPanelCronograma = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCronograma = new javax.swing.JTable();
        btnSalvarCronograma = new javax.swing.JButton();
        btnExportarCronograma = new javax.swing.JButton();
        jPanelAberturaSessaoAbertura = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListCandidatosTotais = new javax.swing.JList();
        btnAddCandidatoAbertura = new javax.swing.JButton();
        btnRemoveCandidatodaPresenca = new javax.swing.JButton();
        btnRemoveCandidatodaPresenca1 = new javax.swing.JButton();
        btnAddCandidatoAbertura1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListCandidatosTotais1 = new javax.swing.JList();
        txtHOraInicioDaSessao = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        btnSalvarCandPresente = new javax.swing.JButton();
        btnExportarAtaDeDefesa = new javax.swing.JButton();
        jPanelPesosDasProvas = new javax.swing.JPanel();
        botaoSalvar = new javax.swing.JButton();
        textEscrita = new javax.swing.JLabel();
        texDidática = new javax.swing.JLabel();
        textMemorial = new javax.swing.JLabel();
        textTitulos = new javax.swing.JLabel();
        textEntrevista = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPesoMemorial = new javax.swing.JFormattedTextField();
        txtEscrita = new javax.swing.JFormattedTextField();
        txtDidatica = new javax.swing.JFormattedTextField();
        txtTitulo = new javax.swing.JFormattedTextField();
        txtEntrevista = new javax.swing.JFormattedTextField();
        jPanelProvaEscrita = new javax.swing.JPanel();
        jPanelProvaDeTitulos = new javax.swing.JPanel();
        jPanelProvaDidatica = new javax.swing.JPanel();
        jPanelDefesaMemorial = new javax.swing.JPanel();
        jPanelResultadoFinal = new javax.swing.JPanel();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuAcoes = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuSuport = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sistema Gerenciador de Concurso");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Instalação");

        jButton2.setText("Cronograma");

        jButton3.setText("Abertura");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Pesos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonsSessaoAberturaLayout = new javax.swing.GroupLayout(jPanelButtonsSessaoAbertura);
        jPanelButtonsSessaoAbertura.setLayout(jPanelButtonsSessaoAberturaLayout);
        jPanelButtonsSessaoAberturaLayout.setHorizontalGroup(
            jPanelButtonsSessaoAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsSessaoAberturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelButtonsSessaoAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelButtonsSessaoAberturaLayout.setVerticalGroup(
            jPanelButtonsSessaoAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsSessaoAberturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Instalação:");

        jLabel2.setText("Local de Sessão de Instalação da Comissão Examinadora:");

        txtLocalSessaoInstalacao.setToolTipText("Exemplo: sala cento e doze do Campus Alegrete");

        jLabel3.setText("Portaria de Nomeação da Banca:");

        txtPortariaNomeacaoDaBanca.setToolTipText("Exemplo: 005/2008 (esta informação constará na ata)");

        jLabel4.setText("Emissor da Portaria de Nomeação da Banca:");

        txtPortariaNomeacaoBanca.setToolTipText("Exemplo: \"Reitoria da Universidade Federal do Pampa\" (esta informação constará na ata)");

        btnSalvarInstalacaoSessao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/sgc/apresentacao/icones/salvar.png"))); // NOI18N
        btnSalvarInstalacaoSessao.setToolTipText("Salvar Registro de Instalação");

        btnGerarAtaInstalacaoSessaoAbertura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/sgc/apresentacao/icones/exportar.png"))); // NOI18N
        btnGerarAtaInstalacaoSessaoAbertura.setToolTipText("Gerar Ata de Instalação");

        javax.swing.GroupLayout jPaneInstalacaoSessaoAberturaLayout = new javax.swing.GroupLayout(jPaneInstalacaoSessaoAbertura);
        jPaneInstalacaoSessaoAbertura.setLayout(jPaneInstalacaoSessaoAberturaLayout);
        jPaneInstalacaoSessaoAberturaLayout.setHorizontalGroup(
            jPaneInstalacaoSessaoAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneInstalacaoSessaoAberturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneInstalacaoSessaoAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneInstalacaoSessaoAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(txtHoraInicioSessaoInstalacao, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addComponent(txtLocalSessaoInstalacao)
                        .addComponent(jLabel3)
                        .addComponent(txtPortariaNomeacaoDaBanca)
                        .addComponent(jLabel4)
                        .addComponent(txtPortariaNomeacaoBanca))
                    .addGroup(jPaneInstalacaoSessaoAberturaLayout.createSequentialGroup()
                        .addComponent(btnSalvarInstalacaoSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGerarAtaInstalacaoSessaoAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPaneInstalacaoSessaoAberturaLayout.setVerticalGroup(
            jPaneInstalacaoSessaoAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneInstalacaoSessaoAberturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(txtHoraInicioSessaoInstalacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLocalSessaoInstalacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPortariaNomeacaoDaBanca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPortariaNomeacaoBanca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPaneInstalacaoSessaoAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarInstalacaoSessao)
                    .addComponent(btnGerarAtaInstalacaoSessaoAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTableCronograma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Atividade", "Data", "Horário", "Local"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableCronograma);

        btnSalvarCronograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/sgc/apresentacao/icones/salvar.png"))); // NOI18N
        btnSalvarCronograma.setToolTipText("Salvar Cronograma");

        btnExportarCronograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/sgc/apresentacao/icones/exportar.png"))); // NOI18N
        btnExportarCronograma.setToolTipText("Exportar Cronograma");
        btnExportarCronograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarCronogramaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCronogramaLayout = new javax.swing.GroupLayout(jPanelCronograma);
        jPanelCronograma.setLayout(jPanelCronogramaLayout);
        jPanelCronogramaLayout.setHorizontalGroup(
            jPanelCronogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCronogramaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCronogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCronogramaLayout.createSequentialGroup()
                        .addComponent(btnSalvarCronograma, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExportarCronograma, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanelCronogramaLayout.setVerticalGroup(
            jPanelCronogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCronogramaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanelCronogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvarCronograma)
                    .addComponent(btnExportarCronograma))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jLabel5.setText("Marque os candidatos presentes na sessão de abertura do concurso:");

        jListCandidatosTotais.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListCandidatosTotais);

        btnAddCandidatoAbertura.setText(">");
        btnAddCandidatoAbertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCandidatoAberturaActionPerformed(evt);
            }
        });

        btnRemoveCandidatodaPresenca.setText("<");
        btnRemoveCandidatodaPresenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveCandidatodaPresencaActionPerformed(evt);
            }
        });

        btnRemoveCandidatodaPresenca1.setText("<<");
        btnRemoveCandidatodaPresenca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveCandidatodaPresenca1ActionPerformed(evt);
            }
        });

        btnAddCandidatoAbertura1.setText(">>");

        jListCandidatosTotais1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListCandidatosTotais1);

        jLabel6.setText("Hora de Início da Sessão de Abertura do Concurso:");

        btnSalvarCandPresente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/sgc/apresentacao/icones/salvar.png"))); // NOI18N
        btnSalvarCandPresente.setToolTipText("Salvar Registro de Instalação");
        btnSalvarCandPresente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCandPresenteActionPerformed(evt);
            }
        });

        btnExportarAtaDeDefesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/sgc/apresentacao/icones/exportar.png"))); // NOI18N
        btnExportarAtaDeDefesa.setToolTipText("Gerar Ata de Instalação");

        javax.swing.GroupLayout jPanelAberturaSessaoAberturaLayout = new javax.swing.GroupLayout(jPanelAberturaSessaoAbertura);
        jPanelAberturaSessaoAbertura.setLayout(jPanelAberturaSessaoAberturaLayout);
        jPanelAberturaSessaoAberturaLayout.setHorizontalGroup(
            jPanelAberturaSessaoAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAberturaSessaoAberturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAberturaSessaoAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAberturaSessaoAberturaLayout.createSequentialGroup()
                        .addComponent(btnSalvarCandPresente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExportarAtaDeDefesa, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAberturaSessaoAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelAberturaSessaoAberturaLayout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jPanelAberturaSessaoAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAddCandidatoAbertura1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRemoveCandidatodaPresenca1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRemoveCandidatodaPresenca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddCandidatoAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel6)
                        .addComponent(txtHOraInicioDaSessao)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanelAberturaSessaoAberturaLayout.setVerticalGroup(
            jPanelAberturaSessaoAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAberturaSessaoAberturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGroup(jPanelAberturaSessaoAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAberturaSessaoAberturaLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnAddCandidatoAbertura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveCandidatodaPresenca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddCandidatoAbertura1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveCandidatodaPresenca1))
                    .addGroup(jPanelAberturaSessaoAberturaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAberturaSessaoAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHOraInicioDaSessao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanelAberturaSessaoAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalvarCandPresente)
                    .addComponent(btnExportarAtaDeDefesa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        botaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/sgc/apresentacao/icones/salvar.png"))); // NOI18N
        botaoSalvar.setToolTipText("Atribuir Pesos");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        textEscrita.setText("Escrita");

        texDidática.setText("Didática");

        textMemorial.setText("Memorial");

        textTitulos.setText("Títulos");

        textEntrevista.setText("Entrevista");

        jLabel7.setText("Determine os pesos das provas, de acordo com o edital do concurso.");

        txtPesoMemorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoMemorialActionPerformed(evt);
            }
        });

        txtDidatica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDidaticaActionPerformed(evt);
            }
        });

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPesosDasProvasLayout = new javax.swing.GroupLayout(jPanelPesosDasProvas);
        jPanelPesosDasProvas.setLayout(jPanelPesosDasProvasLayout);
        jPanelPesosDasProvasLayout.setHorizontalGroup(
            jPanelPesosDasProvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesosDasProvasLayout.createSequentialGroup()
                .addGroup(jPanelPesosDasProvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPesosDasProvasLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanelPesosDasProvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanelPesosDasProvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelPesosDasProvasLayout.createSequentialGroup()
                                    .addComponent(textEntrevista)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtEntrevista))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelPesosDasProvasLayout.createSequentialGroup()
                                    .addGroup(jPanelPesosDasProvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textMemorial)
                                        .addComponent(textEscrita)
                                        .addComponent(texDidática)
                                        .addComponent(textTitulos))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanelPesosDasProvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtDidatica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                        .addComponent(txtEscrita, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPesoMemorial, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTitulo))))))
                    .addGroup(jPanelPesosDasProvasLayout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanelPesosDasProvasLayout.setVerticalGroup(
            jPanelPesosDasProvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPesosDasProvasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPesosDasProvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textMemorial)
                    .addComponent(txtPesoMemorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanelPesosDasProvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEscrita)
                    .addComponent(txtEscrita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPesosDasProvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texDidática)
                    .addComponent(txtDidatica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPesosDasProvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTitulos)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPesosDasProvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEntrevista)
                    .addComponent(txtEntrevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(botaoSalvar)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanelInternoSessaoAberturaLayout = new javax.swing.GroupLayout(jPanelInternoSessaoAbertura);
        jPanelInternoSessaoAbertura.setLayout(jPanelInternoSessaoAberturaLayout);
        jPanelInternoSessaoAberturaLayout.setHorizontalGroup(
            jPanelInternoSessaoAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInternoSessaoAberturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInternoSessaoAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelAberturaSessaoAbertura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPaneInstalacaoSessaoAbertura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCronograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(347, Short.MAX_VALUE))
            .addGroup(jPanelInternoSessaoAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelInternoSessaoAberturaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelPesosDasProvas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelInternoSessaoAberturaLayout.setVerticalGroup(
            jPanelInternoSessaoAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInternoSessaoAberturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInternoSessaoAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCronograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPaneInstalacaoSessaoAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAberturaSessaoAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelInternoSessaoAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelInternoSessaoAberturaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelPesosDasProvas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanelSessaoDeAberturaLayout = new javax.swing.GroupLayout(jPanelSessaoDeAbertura);
        jPanelSessaoDeAbertura.setLayout(jPanelSessaoDeAberturaLayout);
        jPanelSessaoDeAberturaLayout.setHorizontalGroup(
            jPanelSessaoDeAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSessaoDeAberturaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelButtonsSessaoAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelInternoSessaoAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSessaoDeAberturaLayout.setVerticalGroup(
            jPanelSessaoDeAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSessaoDeAberturaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelSessaoDeAberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelInternoSessaoAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelButtonsSessaoAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneInternoDinamico.addTab("Sessão de Abertura", new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/sgc/apresentacao/icones/sessaoDeAbertura.png")), jPanelSessaoDeAbertura); // NOI18N

        javax.swing.GroupLayout jPanelProvaEscritaLayout = new javax.swing.GroupLayout(jPanelProvaEscrita);
        jPanelProvaEscrita.setLayout(jPanelProvaEscritaLayout);
        jPanelProvaEscritaLayout.setHorizontalGroup(
            jPanelProvaEscritaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 875, Short.MAX_VALUE)
        );
        jPanelProvaEscritaLayout.setVerticalGroup(
            jPanelProvaEscritaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        jTabbedPaneInternoDinamico.addTab("Prova Escrita", new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/sgc/apresentacao/icones/provaEscrita.png")), jPanelProvaEscrita); // NOI18N

        javax.swing.GroupLayout jPanelProvaDeTitulosLayout = new javax.swing.GroupLayout(jPanelProvaDeTitulos);
        jPanelProvaDeTitulos.setLayout(jPanelProvaDeTitulosLayout);
        jPanelProvaDeTitulosLayout.setHorizontalGroup(
            jPanelProvaDeTitulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 875, Short.MAX_VALUE)
        );
        jPanelProvaDeTitulosLayout.setVerticalGroup(
            jPanelProvaDeTitulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        jTabbedPaneInternoDinamico.addTab("Prova de Títulos", new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/sgc/apresentacao/icones/provaTitulos.png")), jPanelProvaDeTitulos); // NOI18N

        javax.swing.GroupLayout jPanelProvaDidaticaLayout = new javax.swing.GroupLayout(jPanelProvaDidatica);
        jPanelProvaDidatica.setLayout(jPanelProvaDidaticaLayout);
        jPanelProvaDidaticaLayout.setHorizontalGroup(
            jPanelProvaDidaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 875, Short.MAX_VALUE)
        );
        jPanelProvaDidaticaLayout.setVerticalGroup(
            jPanelProvaDidaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        jTabbedPaneInternoDinamico.addTab("Prova de Didática", new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/sgc/apresentacao/icones/provaDidatica.png")), jPanelProvaDidatica); // NOI18N

        javax.swing.GroupLayout jPanelDefesaMemorialLayout = new javax.swing.GroupLayout(jPanelDefesaMemorial);
        jPanelDefesaMemorial.setLayout(jPanelDefesaMemorialLayout);
        jPanelDefesaMemorialLayout.setHorizontalGroup(
            jPanelDefesaMemorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 875, Short.MAX_VALUE)
        );
        jPanelDefesaMemorialLayout.setVerticalGroup(
            jPanelDefesaMemorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        jTabbedPaneInternoDinamico.addTab("Defesa de Memorial", new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/sgc/apresentacao/icones/defesaMemorial.png")), jPanelDefesaMemorial); // NOI18N

        javax.swing.GroupLayout jPanelResultadoFinalLayout = new javax.swing.GroupLayout(jPanelResultadoFinal);
        jPanelResultadoFinal.setLayout(jPanelResultadoFinalLayout);
        jPanelResultadoFinalLayout.setHorizontalGroup(
            jPanelResultadoFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 875, Short.MAX_VALUE)
        );
        jPanelResultadoFinalLayout.setVerticalGroup(
            jPanelResultadoFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        jTabbedPaneInternoDinamico.addTab("Resultado Final", new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/sgc/apresentacao/icones/resultadoFinal.png")), jPanelResultadoFinal); // NOI18N

        getContentPane().add(jTabbedPaneInternoDinamico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 880, 440));

        jMenuBarPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenuAcoes.setText("Ações");
        jMenuAcoes.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/sgc/apresentacao/icones/reiniciar.png"))); // NOI18N
        jMenuItem1.setText("Reiniciar");
        jMenuAcoes.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/sgc/apresentacao/icones/desligar.png"))); // NOI18N
        jMenuItem2.setText("Sair");
        jMenuAcoes.add(jMenuItem2);

        jMenuBarPrincipal.add(jMenuAcoes);

        jMenuSuport.setText("Suporte");
        jMenuSuport.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/sgc/apresentacao/icones/manualDoSistema.png"))); // NOI18N
        jMenuItem3.setText("Manual do Sistema");
        jMenuSuport.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/sgc/apresentacao/icones/faleConosco.png"))); // NOI18N
        jMenuItem4.setText("Fale Conosco");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuSuport.add(jMenuItem4);

        jMenuBarPrincipal.add(jMenuSuport);

        setJMenuBar(jMenuBarPrincipal);
        jMenuBarPrincipal.getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnExportarCronogramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarCronogramaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportarCronogramaActionPerformed

    private void btnRemoveCandidatodaPresencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveCandidatodaPresencaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveCandidatodaPresencaActionPerformed

    private void btnRemoveCandidatodaPresenca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveCandidatodaPresenca1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveCandidatodaPresenca1ActionPerformed

    private void btnAddCandidatoAberturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCandidatoAberturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddCandidatoAberturaActionPerformed

    private void btnSalvarCandPresenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCandPresenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarCandPresenteActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        //        try {
            //            int pesoProvaEscrita = Integer.parseInt(campoEscrita.getText());
            //            int pesoProvaProvaDidática = Integer.parseInt(campoDidatica.getText());
            //            int pesoProvaMemorial = Integer.parseInt(campoMemorial.getText());
            //            int pesoProvaTitulo = Integer.parseInt(campoTitulos.getText());
            //            int pesoProvaEntrevista = Integer.parseInt(campoEntrevista.getText());
            //            int idPeso = Integer.parseInt(campoCodigo.getText());

            //            Pesoprovas pesoProvas = new Pesoprovas();
            //            pesoProvas.setPesoProvaEscrita(pesoProvaEscrita);
            //            pesoProvas.setPesoProvaDidatica(pesoProvaProvaDidática);
            //            pesoProvas.setPesoProvaMemorial(pesoProvaMemorial);
            //            pesoProvas.setPesoProvaTitulo(pesoProvaTitulo);
            //            pesoProvas.setPesoProvaEntrevista(pesoProvaEntrevista);
            //            pesoProvas.setIdPeso(idPeso);
            //
            //            int totalPeso = pesoProvaEscrita + pesoProvaProvaDidática + pesoProvaMemorial + pesoProvaTitulo + pesoProvaEntrevista;
            //            if (totalPeso != 10) {
                //                JOptionPane.showMessageDialog(null, "A soma do peso das provas deve ser igual a 10.");
                //            } else {
                //                if (pesoProvas.getIdPeso() == 0) {
                    //                    if (pesoProvas.inserir(pesoProvas)) {
                        //                        JOptionPane.showMessageDialog(null, "Peso das provas foi salvo com sucesso!");
                        //                    }
                    //                } else {
                    //                    if (pesoProvas.editar(pesoProvas.getIdPeso(), pesoProvas)) {
                        //                        JOptionPane.showMessageDialog(null, "Peso das provas foi atualizado com sucesso!");
                        //                    }
                    //                }
                //            }
            //        } catch (NumberFormatException e) {
            //            JOptionPane.showMessageDialog(null, "Digite apenas numeros para os pesos.");
            //        }
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void txtPesoMemorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoMemorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoMemorialActionPerformed

    private void txtDidaticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDidaticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDidaticaActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JButton btnAddCandidatoAbertura;
    private javax.swing.JButton btnAddCandidatoAbertura1;
    private javax.swing.JButton btnExportarAtaDeDefesa;
    private javax.swing.JButton btnExportarCronograma;
    private javax.swing.JButton btnGerarAtaInstalacaoSessaoAbertura;
    private javax.swing.JButton btnRemoveCandidatodaPresenca;
    private javax.swing.JButton btnRemoveCandidatodaPresenca1;
    private javax.swing.JButton btnSalvarCandPresente;
    private javax.swing.JButton btnSalvarCronograma;
    private javax.swing.JButton btnSalvarInstalacaoSessao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList jListCandidatosTotais;
    private javax.swing.JList jListCandidatosTotais1;
    private javax.swing.JMenu jMenuAcoes;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu jMenuSuport;
    private javax.swing.JPanel jPaneInstalacaoSessaoAbertura;
    private javax.swing.JPanel jPanelAberturaSessaoAbertura;
    private javax.swing.JPanel jPanelButtonsSessaoAbertura;
    private javax.swing.JPanel jPanelCronograma;
    private javax.swing.JPanel jPanelDefesaMemorial;
    private javax.swing.JPanel jPanelInternoSessaoAbertura;
    private javax.swing.JPanel jPanelPesosDasProvas;
    private javax.swing.JPanel jPanelProvaDeTitulos;
    private javax.swing.JPanel jPanelProvaDidatica;
    private javax.swing.JPanel jPanelProvaEscrita;
    private javax.swing.JPanel jPanelResultadoFinal;
    private javax.swing.JPanel jPanelSessaoDeAbertura;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPaneInternoDinamico;
    private javax.swing.JTable jTableCronograma;
    private javax.swing.JLabel texDidática;
    private javax.swing.JLabel textEntrevista;
    private javax.swing.JLabel textEscrita;
    private javax.swing.JLabel textMemorial;
    private javax.swing.JLabel textTitulos;
    private javax.swing.JFormattedTextField txtDidatica;
    private javax.swing.JFormattedTextField txtEntrevista;
    private javax.swing.JFormattedTextField txtEscrita;
    private javax.swing.JFormattedTextField txtHOraInicioDaSessao;
    private javax.swing.JFormattedTextField txtHoraInicioSessaoInstalacao;
    private javax.swing.JTextField txtLocalSessaoInstalacao;
    private javax.swing.JFormattedTextField txtPesoMemorial;
    private javax.swing.JTextField txtPortariaNomeacaoBanca;
    private javax.swing.JTextField txtPortariaNomeacaoDaBanca;
    private javax.swing.JFormattedTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
