/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unipampa.sgc.apresentacao;

/**
 *
 * @author GabrielBMoro
 */
public class JanelaCriarConcurso extends javax.swing.JFrame {

    public static int STATUS_CRIACAO_CONCURSO=0;
    /**
     * Creates new form JFrameCriarConcurso
     */
    public JanelaCriarConcurso() {
        initComponents();
        setTitle("Criar Concurso");
        panelCriarConcurso1.getPanelDadosGerais().setVisible(true);
        panelCriarConcurso1.getPanelBanca().setVisible(false);
        panelCriarConcurso1.getPaneCandidatosInscritos().setVisible(false);
        panelCriarConcurso1.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCriarConcurso1 = new br.unipampa.sgc.apresentacao.panelCriarConcurso();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelCriarConcurso1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelCriarConcurso1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.unipampa.sgc.apresentacao.panelCriarConcurso panelCriarConcurso1;
    // End of variables declaration//GEN-END:variables

 public panelCriarConcurso getPanelCriarConcurso(){
     return this.panelCriarConcurso1;
 }

    
}
