/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unipampa.sgc.apresentacao;

import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bruning
 */
public class JanelaCriteriosAvaliacao extends javax.swing.JFrame {

    private DefaultTableModel modeloTableCriterios;

    /**
     * Creates new form JanelaCriteriosAvaliacao
     */
    public JanelaCriteriosAvaliacao() {
        initComponents();
      this.modeloTableCriterios = (DefaultTableModel) this.jTableCriterios.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDefinirCriterios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCriterios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtNomeCriterio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPesoCriterio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bntAddCriterio = new javax.swing.JButton();
        bntRemoverCriterio = new javax.swing.JButton();
        bntSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelDefinirCriterios.setBorder(javax.swing.BorderFactory.createTitledBorder("Definir Critérios"));

        jTableCriterios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Critério", "Peso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableCriterios);

        jLabel1.setText("Critério");

        txtNomeCriterio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCriterioActionPerformed(evt);
            }
        });

        jLabel2.setText("Peso");

        txtPesoCriterio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoCriterioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Observação: O somatórios dos pesos dos critérios das provas tem que ser igual a 10.");

        bntAddCriterio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/sgc/apresentacao/icones/incluir.png"))); // NOI18N
        bntAddCriterio.setToolTipText("Adiconar Critério");

        bntRemoverCriterio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/sgc/apresentacao/icones/remover.png"))); // NOI18N
        bntRemoverCriterio.setToolTipText("Remover Critério");

        bntSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/sgc/apresentacao/icones/salvar.png"))); // NOI18N
        bntSalvar.setToolTipText("Salvar Dados");

        javax.swing.GroupLayout jPanelDefinirCriteriosLayout = new javax.swing.GroupLayout(jPanelDefinirCriterios);
        jPanelDefinirCriterios.setLayout(jPanelDefinirCriteriosLayout);
        jPanelDefinirCriteriosLayout.setHorizontalGroup(
            jPanelDefinirCriteriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDefinirCriteriosLayout.createSequentialGroup()
                .addGroup(jPanelDefinirCriteriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelDefinirCriteriosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDefinirCriteriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtNomeCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDefinirCriteriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPesoCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntAddCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDefinirCriteriosLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(bntRemoverCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDefinirCriteriosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bntSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelDefinirCriteriosLayout.setVerticalGroup(
            jPanelDefinirCriteriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDefinirCriteriosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addGroup(jPanelDefinirCriteriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanelDefinirCriteriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDefinirCriteriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNomeCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPesoCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bntAddCriterio))
                .addGap(17, 17, 17)
                .addGroup(jPanelDefinirCriteriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDefinirCriteriosLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(bntRemoverCriterio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(bntSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bntAddCriterio.getAccessibleContext().setAccessibleName("addCriterios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelDefinirCriterios, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDefinirCriterios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeCriterioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCriterioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCriterioActionPerformed

    private void txtPesoCriterioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoCriterioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoCriterioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCriteriosAvaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCriteriosAvaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCriteriosAvaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCriteriosAvaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaCriteriosAvaliacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAddCriterio;
    private javax.swing.JButton bntRemoverCriterio;
    private javax.swing.JButton bntSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelDefinirCriterios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCriterios;
    private javax.swing.JTextField txtNomeCriterio;
    private javax.swing.JTextField txtPesoCriterio;
    // End of variables declaration//GEN-END:variables
   
    public LinkedList<String> recuperarDadosPanelCandidatos() {
        LinkedList<String> dados = new LinkedList<>();
        for (int row = 0; row < this.modeloTableCriterios.getRowCount(); row++) {
            for (int col = 0; col < this.modeloTableCriterios.getColumnCount(); col++) {
                if (this.modeloTableCriterios.getValueAt(row, col) == null) {
                    return null;
                } else {
                    Object value = this.modeloTableCriterios.getValueAt(row, col);
                    String valueText = String.valueOf(value);
                    dados.add(valueText);
                }
            }
        }
        return dados;
    }
    
    
    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @param jLabel1 the jLabel1 to set
     */
    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @param jLabel2 the jLabel2 to set
     */
    public void setjLabel2(javax.swing.JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    /**
     * @return the jLabel3
     */
    public javax.swing.JLabel getjLabel3() {
        return jLabel3;
    }

    /**
     * @param jLabel3 the jLabel3 to set
     */
    public void setjLabel3(javax.swing.JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanelDefinirCriterios() {
        return jPanelDefinirCriterios;
    }

    /**
     * @param jPanelDefinirCriterios the jPanel1 to set
     */
    public void setjPanelDefinirCriterios(javax.swing.JPanel jPanelDefinirCriterios) {
        this.jPanelDefinirCriterios = jPanelDefinirCriterios;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the jTableCriterios
     */
    public javax.swing.JTable getjTableCriterios() {
        return jTableCriterios;
    }

    /**
     * @param jTableCriterios the jTableCriterios to set
     */
    public void setjTableCriterios(javax.swing.JTable jTableCriterios) {
        this.jTableCriterios = jTableCriterios;
    }

    /**
     * @return the txtNomeCriterio
     */
    public javax.swing.JTextField getTxtNomeCriterio() {
        return txtNomeCriterio;
    }

    /**
     * @param txtNomeCriterio the txtNomeCriterio to set
     */
    public void setTxtNomeCriterio(javax.swing.JTextField txtNomeCriterio) {
        this.txtNomeCriterio = txtNomeCriterio;
    }

    /**
     * @return the txtPesoCriterio
     */
    public javax.swing.JTextField getTxtPesoCriterio() {
        return txtPesoCriterio;
    }

    /**
     * @param txtPesoCriterio the txtPesoCriterio to set
     */
    public void setTxtPesoCriterio(javax.swing.JTextField txtPesoCriterio) {
        this.txtPesoCriterio = txtPesoCriterio;
    }

    /**
     * @return the bntAddCriterio
     */
    public javax.swing.JButton getBntAddCriterio() {
        return bntAddCriterio;
    }

    /**
     * @param bntAddCriterio the bntAddCriterio to set
     */
    public void setBntAddCriterio(javax.swing.JButton bntAddCriterio) {
        this.bntAddCriterio = bntAddCriterio;
    }

    /**
     * @return the bntRemoverCriterio
     */
    public javax.swing.JButton getBntRemoverCriterio() {
        return bntRemoverCriterio;
    }

    /**
     * @param bntRemoverCriterio the bntRemoverCriterio to set
     */
    public void setBntRemoverCriterio(javax.swing.JButton bntRemoverCriterio) {
        this.bntRemoverCriterio = bntRemoverCriterio;
    }

    /**
     * @return the bntSalvar
     */
    public javax.swing.JButton getBntSalvar() {
        return bntSalvar;
    }

    /**
     * @param bntSalvar the bntSalvar to set
     */
    public void setBntSalvar(javax.swing.JButton bntSalvar) {
        this.bntSalvar = bntSalvar;
    }

    /**
     * @return the modeloTableCandidatos
     */
    public DefaultTableModel getModeloTableCriterios() {
        return modeloTableCriterios;
    }

    /**
     * @param modeloTableCriterios the modeloTableCandidatos to set
     */
    public void setModeloTableCriterios(DefaultTableModel modeloTableCriterios) {
        this.modeloTableCriterios = modeloTableCriterios;
    }
}
